language: php

php:
  - 7.2

env:
  - REPORT_EXIT_STATUS=1

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install libsdl2-dev

before_script:
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=sdl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - ./run-tests.php -q -p $(which php) --show-diff

