language: php

php:
  - 7.2

env:
  - REPORT_EXIT_STATUS=1

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
    cd SDL2-2.0.8
    ./configure
    make
    sudo make install

install:
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev

before_script:
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=sdl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - chmod +x run-tests.php

script:
  - ./run-tests.php -q -p $(which php) --show-diff

