language: php

php:
  - 5.6
  - 5.5

env:
  - REPORT_EXIT_STATUS=1

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install libsdl2-dev

before_script:
  #- wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
  #- cd SDL2-2.0.3 && ./configure && make -j && sudo make install && cd ..
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=sdl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  # - TEST_PHP_EXECUTABLE=$(which php) $TEST_PHP_EXECUTABLE run-tests.php -n -d extension_dir=$MODULES -d extension=sdl.so -q -x --show-diff
  - TEST_PHP_EXECUTABLE=$(which php) make test

