language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
  - REPORT_EXIT_STATUS=1

before_script:
  - wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
  - cd SDL2-2.0.3 && ./configure && make -j && sudo make install && cd ..
  # - sudo apt-get install libsdl2-dev
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=sdl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - php run-tests.php -n -d extension_dir=$MODULES -d extension=sdl.so -q -x --show-diff

