/*
  +----------------------------------------------------------------------+
  | PHP Version 5                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2013 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Authors: Santiago Lizardo <santiagolizardo@php.net>                  |
  |          Remi Collet <remi@php.net>                                  |
  +----------------------------------------------------------------------+
*/

/* $Id$ */ 

/*
  +----------------------------------------------------------------------+
  | wrapper for SDL2/SDL_keyboard.h, SDL_keycode.h, SDL_scancode.h       |
  +----------------------------------------------------------------------+
*/

#include "php_sdl.h"
#include "keyboard.h"


/* {{{ sdl_keyboard_functions[] */
static zend_function_entry sdl_keyboard_functions[] = {
	ZEND_FE_END
};
/* }}} */


/* {{{ MINIT */
PHP_MINIT_FUNCTION(sdl_keyboard)
{
	/* from SDL_scancode.h */
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_UNKNOWN", SDL_SCANCODE_UNKNOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_A", SDL_SCANCODE_A, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_B", SDL_SCANCODE_B, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_C", SDL_SCANCODE_C, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_D", SDL_SCANCODE_D, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_E", SDL_SCANCODE_E, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F", SDL_SCANCODE_F, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_G", SDL_SCANCODE_G, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_H", SDL_SCANCODE_H, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_I", SDL_SCANCODE_I, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_J", SDL_SCANCODE_J, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_K", SDL_SCANCODE_K, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_L", SDL_SCANCODE_L, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_M", SDL_SCANCODE_M, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_N", SDL_SCANCODE_N, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_O", SDL_SCANCODE_O, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_P", SDL_SCANCODE_P, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Q", SDL_SCANCODE_Q, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_R", SDL_SCANCODE_R, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_S", SDL_SCANCODE_S, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_T", SDL_SCANCODE_T, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_U", SDL_SCANCODE_U, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_V", SDL_SCANCODE_V, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_W", SDL_SCANCODE_W, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_X", SDL_SCANCODE_X, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Y", SDL_SCANCODE_Y, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_Z", SDL_SCANCODE_Z, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_1", SDL_SCANCODE_1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_2", SDL_SCANCODE_2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_3", SDL_SCANCODE_3, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_4", SDL_SCANCODE_4, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_5", SDL_SCANCODE_5, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_6", SDL_SCANCODE_6, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_7", SDL_SCANCODE_7, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_8", SDL_SCANCODE_8, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_9", SDL_SCANCODE_9, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_0", SDL_SCANCODE_0, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RETURN", SDL_SCANCODE_RETURN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_ESCAPE", SDL_SCANCODE_ESCAPE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BACKSPACE", SDL_SCANCODE_BACKSPACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_TAB", SDL_SCANCODE_TAB, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SPACE", SDL_SCANCODE_SPACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MINUS", SDL_SCANCODE_MINUS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_EQUALS", SDL_SCANCODE_EQUALS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LEFTBRACKET", SDL_SCANCODE_LEFTBRACKET, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RIGHTBRACKET", SDL_SCANCODE_RIGHTBRACKET, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BACKSLASH", SDL_SCANCODE_BACKSLASH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_NONUSHASH", SDL_SCANCODE_NONUSHASH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SEMICOLON", SDL_SCANCODE_SEMICOLON, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APOSTROPHE", SDL_SCANCODE_APOSTROPHE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_GRAVE", SDL_SCANCODE_GRAVE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_COMMA", SDL_SCANCODE_COMMA, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PERIOD", SDL_SCANCODE_PERIOD, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SLASH", SDL_SCANCODE_SLASH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CAPSLOCK", SDL_SCANCODE_CAPSLOCK, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F1", SDL_SCANCODE_F1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F2", SDL_SCANCODE_F2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F3", SDL_SCANCODE_F3, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F4", SDL_SCANCODE_F4, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F5", SDL_SCANCODE_F5, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F6", SDL_SCANCODE_F6, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F7", SDL_SCANCODE_F7, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F8", SDL_SCANCODE_F8, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F9", SDL_SCANCODE_F9, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F10", SDL_SCANCODE_F10, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F11", SDL_SCANCODE_F11, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F12", SDL_SCANCODE_F12, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PRINTSCREEN", SDL_SCANCODE_PRINTSCREEN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SCROLLLOCK", SDL_SCANCODE_SCROLLLOCK, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAUSE", SDL_SCANCODE_PAUSE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INSERT", SDL_SCANCODE_INSERT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_HOME", SDL_SCANCODE_HOME, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAGEUP", SDL_SCANCODE_PAGEUP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DELETE", SDL_SCANCODE_DELETE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_END", SDL_SCANCODE_END, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PAGEDOWN", SDL_SCANCODE_PAGEDOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RIGHT", SDL_SCANCODE_RIGHT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LEFT", SDL_SCANCODE_LEFT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DOWN", SDL_SCANCODE_DOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_UP", SDL_SCANCODE_UP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_NUMLOCKCLEAR", SDL_SCANCODE_NUMLOCKCLEAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_DIVIDE", SDL_SCANCODE_KP_DIVIDE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MULTIPLY", SDL_SCANCODE_KP_MULTIPLY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MINUS", SDL_SCANCODE_KP_MINUS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PLUS", SDL_SCANCODE_KP_PLUS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_ENTER", SDL_SCANCODE_KP_ENTER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_1", SDL_SCANCODE_KP_1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_2", SDL_SCANCODE_KP_2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_3", SDL_SCANCODE_KP_3, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_4", SDL_SCANCODE_KP_4, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_5", SDL_SCANCODE_KP_5, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_6", SDL_SCANCODE_KP_6, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_7", SDL_SCANCODE_KP_7, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_8", SDL_SCANCODE_KP_8, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_9", SDL_SCANCODE_KP_9, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_0", SDL_SCANCODE_KP_0, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PERIOD", SDL_SCANCODE_KP_PERIOD, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_NONUSBACKSLASH", SDL_SCANCODE_NONUSBACKSLASH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APPLICATION", SDL_SCANCODE_APPLICATION, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_POWER", SDL_SCANCODE_POWER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_EQUALS", SDL_SCANCODE_KP_EQUALS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F13", SDL_SCANCODE_F13, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F14", SDL_SCANCODE_F14, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F15", SDL_SCANCODE_F15, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F16", SDL_SCANCODE_F16, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F17", SDL_SCANCODE_F17, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F18", SDL_SCANCODE_F18, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F19", SDL_SCANCODE_F19, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F20", SDL_SCANCODE_F20, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F21", SDL_SCANCODE_F21, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F22", SDL_SCANCODE_F22, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F23", SDL_SCANCODE_F23, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_F24", SDL_SCANCODE_F24, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_EXECUTE", SDL_SCANCODE_EXECUTE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_HELP", SDL_SCANCODE_HELP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MENU", SDL_SCANCODE_MENU, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SELECT", SDL_SCANCODE_SELECT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_STOP", SDL_SCANCODE_STOP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AGAIN", SDL_SCANCODE_AGAIN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_UNDO", SDL_SCANCODE_UNDO, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CUT", SDL_SCANCODE_CUT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_COPY", SDL_SCANCODE_COPY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PASTE", SDL_SCANCODE_PASTE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_FIND", SDL_SCANCODE_FIND, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MUTE", SDL_SCANCODE_MUTE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_VOLUMEUP", SDL_SCANCODE_VOLUMEUP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_VOLUMEDOWN", SDL_SCANCODE_VOLUMEDOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_COMMA", SDL_SCANCODE_KP_COMMA, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_EQUALSAS400", SDL_SCANCODE_KP_EQUALSAS400, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL1", SDL_SCANCODE_INTERNATIONAL1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL2", SDL_SCANCODE_INTERNATIONAL2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL3", SDL_SCANCODE_INTERNATIONAL3, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL4", SDL_SCANCODE_INTERNATIONAL4, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL5", SDL_SCANCODE_INTERNATIONAL5, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL6", SDL_SCANCODE_INTERNATIONAL6, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL7", SDL_SCANCODE_INTERNATIONAL7, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL8", SDL_SCANCODE_INTERNATIONAL8, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_INTERNATIONAL9", SDL_SCANCODE_INTERNATIONAL9, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG1", SDL_SCANCODE_LANG1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG2", SDL_SCANCODE_LANG2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG3", SDL_SCANCODE_LANG3, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG4", SDL_SCANCODE_LANG4, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG5", SDL_SCANCODE_LANG5, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG6", SDL_SCANCODE_LANG6, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG7", SDL_SCANCODE_LANG7, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG8", SDL_SCANCODE_LANG8, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LANG9", SDL_SCANCODE_LANG9, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_ALTERASE", SDL_SCANCODE_ALTERASE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SYSREQ", SDL_SCANCODE_SYSREQ, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CANCEL", SDL_SCANCODE_CANCEL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CLEAR", SDL_SCANCODE_CLEAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_PRIOR", SDL_SCANCODE_PRIOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RETURN2", SDL_SCANCODE_RETURN2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SEPARATOR", SDL_SCANCODE_SEPARATOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_OUT", SDL_SCANCODE_OUT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_OPER", SDL_SCANCODE_OPER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CLEARAGAIN", SDL_SCANCODE_CLEARAGAIN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CRSEL", SDL_SCANCODE_CRSEL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_EXSEL", SDL_SCANCODE_EXSEL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_00", SDL_SCANCODE_KP_00, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_000", SDL_SCANCODE_KP_000, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_THOUSANDSSEPARATOR", SDL_SCANCODE_THOUSANDSSEPARATOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DECIMALSEPARATOR", SDL_SCANCODE_DECIMALSEPARATOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CURRENCYUNIT", SDL_SCANCODE_CURRENCYUNIT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CURRENCYSUBUNIT", SDL_SCANCODE_CURRENCYSUBUNIT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_LEFTPAREN", SDL_SCANCODE_KP_LEFTPAREN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_RIGHTPAREN", SDL_SCANCODE_KP_RIGHTPAREN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_LEFTBRACE", SDL_SCANCODE_KP_LEFTBRACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_RIGHTBRACE", SDL_SCANCODE_KP_RIGHTBRACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_TAB", SDL_SCANCODE_KP_TAB, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_BACKSPACE", SDL_SCANCODE_KP_BACKSPACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_A", SDL_SCANCODE_KP_A, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_B", SDL_SCANCODE_KP_B, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_C", SDL_SCANCODE_KP_C, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_D", SDL_SCANCODE_KP_D, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_E", SDL_SCANCODE_KP_E, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_F", SDL_SCANCODE_KP_F, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_XOR", SDL_SCANCODE_KP_XOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_POWER", SDL_SCANCODE_KP_POWER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PERCENT", SDL_SCANCODE_KP_PERCENT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_LESS", SDL_SCANCODE_KP_LESS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_GREATER", SDL_SCANCODE_KP_GREATER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_AMPERSAND", SDL_SCANCODE_KP_AMPERSAND, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_DBLAMPERSAND", SDL_SCANCODE_KP_DBLAMPERSAND, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_VERTICALBAR", SDL_SCANCODE_KP_VERTICALBAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_DBLVERTICALBAR", SDL_SCANCODE_KP_DBLVERTICALBAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_COLON", SDL_SCANCODE_KP_COLON, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_HASH", SDL_SCANCODE_KP_HASH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_SPACE", SDL_SCANCODE_KP_SPACE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_AT", SDL_SCANCODE_KP_AT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_EXCLAM", SDL_SCANCODE_KP_EXCLAM, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMSTORE", SDL_SCANCODE_KP_MEMSTORE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMRECALL", SDL_SCANCODE_KP_MEMRECALL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMCLEAR", SDL_SCANCODE_KP_MEMCLEAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMADD", SDL_SCANCODE_KP_MEMADD, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMSUBTRACT", SDL_SCANCODE_KP_MEMSUBTRACT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMMULTIPLY", SDL_SCANCODE_KP_MEMMULTIPLY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_MEMDIVIDE", SDL_SCANCODE_KP_MEMDIVIDE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_PLUSMINUS", SDL_SCANCODE_KP_PLUSMINUS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_CLEAR", SDL_SCANCODE_KP_CLEAR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_CLEARENTRY", SDL_SCANCODE_KP_CLEARENTRY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_BINARY", SDL_SCANCODE_KP_BINARY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_OCTAL", SDL_SCANCODE_KP_OCTAL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_DECIMAL", SDL_SCANCODE_KP_DECIMAL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KP_HEXADECIMAL", SDL_SCANCODE_KP_HEXADECIMAL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LCTRL", SDL_SCANCODE_LCTRL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LSHIFT", SDL_SCANCODE_LSHIFT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LALT", SDL_SCANCODE_LALT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_LGUI", SDL_SCANCODE_LGUI, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RCTRL", SDL_SCANCODE_RCTRL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RSHIFT", SDL_SCANCODE_RSHIFT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RALT", SDL_SCANCODE_RALT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_RGUI", SDL_SCANCODE_RGUI, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MODE", SDL_SCANCODE_MODE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AUDIONEXT", SDL_SCANCODE_AUDIONEXT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AUDIOPREV", SDL_SCANCODE_AUDIOPREV, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AUDIOSTOP", SDL_SCANCODE_AUDIOSTOP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AUDIOPLAY", SDL_SCANCODE_AUDIOPLAY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AUDIOMUTE", SDL_SCANCODE_AUDIOMUTE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MEDIASELECT", SDL_SCANCODE_MEDIASELECT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_WWW", SDL_SCANCODE_WWW, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_MAIL", SDL_SCANCODE_MAIL, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_CALCULATOR", SDL_SCANCODE_CALCULATOR, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_COMPUTER", SDL_SCANCODE_COMPUTER, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_SEARCH", SDL_SCANCODE_AC_SEARCH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_HOME", SDL_SCANCODE_AC_HOME, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_BACK", SDL_SCANCODE_AC_BACK, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_FORWARD", SDL_SCANCODE_AC_FORWARD, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_STOP", SDL_SCANCODE_AC_STOP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_REFRESH", SDL_SCANCODE_AC_REFRESH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_AC_BOOKMARKS", SDL_SCANCODE_AC_BOOKMARKS, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BRIGHTNESSDOWN", SDL_SCANCODE_BRIGHTNESSDOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_BRIGHTNESSUP", SDL_SCANCODE_BRIGHTNESSUP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_DISPLAYSWITCH", SDL_SCANCODE_DISPLAYSWITCH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KBDILLUMTOGGLE", SDL_SCANCODE_KBDILLUMTOGGLE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KBDILLUMDOWN", SDL_SCANCODE_KBDILLUMDOWN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_KBDILLUMUP", SDL_SCANCODE_KBDILLUMUP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_EJECT", SDL_SCANCODE_EJECT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_SLEEP", SDL_SCANCODE_SLEEP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APP1", SDL_SCANCODE_APP1, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_SCANCODE_APP2", SDL_SCANCODE_APP2, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SDL_NUM_SCANCODES", SDL_NUM_SCANCODES, CONST_CS | CONST_PERSISTENT);

	return (zend_register_functions(NULL, sdl_keyboard_functions, NULL, MODULE_PERSISTENT TSRMLS_CC));
}
/* }}} */
